### ISSUE TITLE
Consensus sequence file cannot be found

### ISSUE THREAD

**Issue by antoine4ucsd** [ozagordi/minvar_ms_analysis#1]
Hi,
I installed VirVarSeq and dependencies on my Mac and I tried to test the install with ./run.sh
It does create a big log file (~1Go) along with the results subfolder and the map_vs_ref files (4 sai files) in the subdirectory but after several minutes it stops and no other results are recorded.
Looking at the log file, it seems like the consensus seq was not created
I am attaching the last lines of the log file.
I also tried with my own set of data and got the same issue.

Any thoughts?

thanks!
a

[VirVarSeq.log_ends.txt](https://github.com/ozagordi/minvar_ms_analysis/files/955516/VirVarSeq.log_ends.txt)

**Comment by ozagordi** [comment]
Hi Antoine,
just to make sure, your question is on how to reproduce the results from the paper where we presented MinVar, or about VirVarSeq in general?
The repository here is only relevant in the first case. The script [`run.sh`](https://github.com/ozagordi/minvar_ms_analysis/blob/master/mixes_Miseq_VirVarSeq/run.sh) is only meant to be run by snakemake. In each directory (like `mixes_Miseq_VirVarSeq`) you should run `snakemake` and, provided you have downloaded the original data in the correct path, you should be able to reobtain my results.

If your question is about VirVarSeq in general then you should contact its developers.

I hope that helps. Closing this for now, but please let me know if you want to reproduce our results, I will try to help you.

Best.
    Osvaldo

**Comment by antoine4ucsd** [comment]
thanks Osvaldo and sorry for the confusion. My question had to to with VirVarSeq in general, sorry for that.

Best,
a
