### ISSUE TITLE
awk error - fatal: division by zero attempted

### ISSUE THREAD

**Issue by MigleSur** [ozagordi/minvar_ms_analysis#2]
Dear Authors of Virvarseq. 

First, we in our group are very glad to use your tool and find it useful. However, when running it for some samples, we get an awk division by zero error. The input files are not empty and are we haven't been able to identify how they could differ from other successfully run files. 

Have you experienced this error before and know how to fix this issue?

Best,
Migle

**Comment by ozagordi** [comment]
Hi Migle.
I’m afraid you’re writing this question in the wrong place.

Closing it as it should be directed to VirVarSeq developers.
